name: Compliance Check

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'
  pull_request:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'

jobs:
  compliance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run compliance check
        run: |
          npm run lint
          npm run format
          npm run typecheck
          npm run build
